name: 'Cloudflare Pages Await'
description: 'Wait for Cloudflare Pages to build'
author: 'WalshyDev'
inputs:
  accountEmail:
    description: 'Cloudflare account email (Not recommended)'
    required: false
  apiKey:
    description: 'Cloudflare API Key (Not recommended)'
    required: false
  apiToken:
    description: 'Cloudflare API Token (Recommended)'
    required: false

  accountId:
    description: 'Cloudflare account ID'
    required: true
  project:
    description: 'Pages project name'
    required: true
  githubToken:
    description: 'GitHub Token to use for deployments (GITHUB_TOKEN secret or your own token!) - OPTIONAL (Only used for GitHub Deployments)'
    required: false
  commitHash:
    description: 'The commit hash of the commit triggered the target deployment'
    required: false
outputs:
  id:
    description: 'Deployment ID'
  environment:
    description: 'Environment for this deployment, either "production" or "preview"'
  url:
    description: 'URL of the deployment'
  alias:
    description: 'Alias URL of the branch (for example: fix-navbar.project.pages.dev)'
  success:
    description: 'If the build passed or failed'
runs:
  using: 'node20'
  main: 'dist/action.js'
branding:
  icon: 'cloud'
  color: 'orange'
